language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
script:
  - yarn test
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
